name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branchs:
      - main
  schedule:
    - cron: '0 0 * * 0'

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v2
      # Set up a Node.js environment using the specified node version.
      - uses: 
        with:
          node-version: [16, 18]

      # Install the dependencies.
      - run: npm install -y

      # Run the tests.
      - run: npm test

      # Run the linter.
      - run: npm lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
